/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xy_ffmpeg_VideoPlayer */

#ifndef _Included_com_xy_ffmpeg_VideoPlayer
#define _Included_com_xy_ffmpeg_VideoPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
* Class:     com_xy_ffmpeg_VideoPlayer
* Method:    test
* Signature: ()I
*/
JNIEXPORT jstring JNICALL Java_com_xy_ffmpeg_VideoPlayer_test
        (JNIEnv *, jobject);

/*
 * Class:     com_xy_ffmpeg_VideoPlayer
 * Method:    playVideo
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_xy_ffmpeg_VideoPlayer_playVideo
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
